services:
  - docker

env:
  - SONAR_SCANNER_VERSION=4.6.1.2450 # Find the latest version in the "Linux" link on this page:
  - SONAR_SERVER_URL="https://sonarcloud.io"
  - BUILD_WRAPPER_OUT_DIR=build_wrapper_output_directory # Directory where build-wrapper output will be placed
  - LOCAL_BUILD_DIR="ci-slingshot-build"
  - LOCAL_COVERAGE_DIR="ci-slingshot-coverage"
  - CONTAINER_REPO_DIR="/usr/src/ci-slingshot"
  - CONTAINER_SOURCE_DIR="/usr/src/ci-slingshot/cpp"
  - CONTAINER_BUILD_DIR="/usr/build/ci-slingshot"
  - CONTAINER_COVERAGE_DIR="/usr/sonar/ci-slingshot"

script:
  - bash scripts/build-stage.sh

after_success:
  - bash scripts/tests-stage.sh
  - bash scripts/analysis-stage.sh
